language: node_js

sudo: required

node_js:
  - "4.8.1"

services:
  - docker

before_install:
  - sudo apt-get install -y make
  - make test-image deps

install:
  - npm install

env:
  - GROUP=yanksin COMMIT="${TRAVIS_COMMIT}" TAG="${TRAVIS_TAG}" REPO=front-end;

script:
  - make test

after_success:
  - set -e
  - if [ -z "${DOCKER_PASS}" ]; then echo "Build triggered by external PR. Skipping docker push" && exit 0; fi
  - docker login -u "${DOCKER_USER}" -p "${DOCKER_PASS}";
  - ./scripts/build.sh
  - ./test/container.sh
  - ./scripts/push.sh
